apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
    tier: database
    environment: prod
    purpose: credentials
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "example_password"
  POSTGRES_DB: "users"
  POSTGRES_HOST: "postgres-service"     # в качестве хоста указываем имя сервиса для постгреса
  POSTGRES_PORT: "5432"